# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mathieu Tanguy
title: Mecatronic Engineer
email: mathieu@tanguym.eu
address: 11 rue Saint Michel, 44260 Savenay FRANCE
# website: https://mttng.github.io/online-resume/

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: mttng
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Website
  icon: fas fa-globe
  url: https://mttng.github.io/online-resume/
- title: Pdf Download
  icon: far fa-file-pdf
  url: https://mttng.github.io/online-resume/raw/main/pdf/cv.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Mathieu, I'm a industrial automation engineer. I live with my wife and kids near Nantes in France.<br>
  Since 4 years, I work as a technical office manager which consists of managing a team made up of support & application engineers.
  My main goals are to plan & prioritize technical actions, develop soft and technical skills of all my team's member.
  Although my position give me more responsabilities and administrative work, I'm still involved in complex strategic customer projects.
  I am most skilled in: <mark>Software architecture</mark>, <mark>Motion control</mark>, <mark>CNC</mark>, <mark>Robtotic</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Flexible transport system
        # link: https://www.youtube.com/watch?v=VJN8IgHODj4
        # link_text: Machine presentation
        additional_links:
          - title:  Acopostrak
            icon: fas fa-globe
            url: https://www.br-automation.com/en/products/mechatronic-systems/acopostrak/
          - title:  Can Collar
            icon: fa fa-youtube
            url: https://www.br-automation.com/en/products/mechatronic-systems/acopostrak/
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Thanks to this new type of technology, Machine is fully flexible. it can group cans by 2, 3, 4 and more with almost no change over.
          It was possible thanks to encoder emulation, cam profile and cycling positionning.
          I was involved from the begining in pre-sales until now where the machine is now in serial production.
          For this innovative project I had the chance to be in close cooperation with R&D & other services.
          
      - layout: left
        title: Integrated robot
        # link: https://www.youtube.com/watch?v=VJN8IgHODj4
        # link_text: Machine presentation
        additional_links:
          - title:  Cetec
            icon: fa fa-youtube
            url: https://www.youtube.com/watch?v=xE7J6ICQw88
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Robot is controlled by the PLC and fully synchronized with the rest of the machine.
          Gripper follows the height of vertical conveyor while still placing bags.
      - layout: left
        title: CNC Machine
        additional_links:
          - title:  BDM
            icon: fa fa-youtube
            url: https://www.youtube.com/watch?v=T4fu1nRZKFs
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Machine cuts and machines aluminium or plastic profiles. CNC engine is integrated inside the main CPU.
          Customer could get rid of an expensive and non modular dedicated CNC controller.
          This was my first project as application engineer
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: B&R Automation
        link: br-automation.com
        # link_text: boringcompany.com
        sub_title: Technical Office Manager
        caption: Feb 2018 - Present (Nantes)
        description: | # this will include new lines to allow paragraphs
            After many year as application engineer, I got promoted as technical office manager.
            I leaded up to 7 local application & support engineers in Nantes offices.
            My main mission is to plan & prioritize technical actions while making making sure all my colleague have enough skills to succeed.
            Even with this new responsability, I'm still involved technically in strategic customer project.

      - layout: left
        title: B&R Automation
        link: br-automation.com
        # link_text: boringcompany.com
        sub_title: Application Engineer
        caption: Feb 2010 - Feb 2018 (Paris & Nantes)
        description: | # this will include new lines to allow paragraphs
          This position has been for me very challenging as the spectrum is large:
          - technically supporting customer remotly and on site.
          - Assisting customer on his project from prototype phase to serial production.
          - Holding customer and internal training.
          - Software architecture and analysis.
          - Définir des architectures matérielles.
          - Participating to pre-sales project.

      - layout: left
        title: B&R Automation
        link: https://www.br-automation.com/en/career/working-at-br/engineering-camp/
        link_text: Engineering Camp
        sub_title: Training program
        caption: Sept 2009 - Jan 2010 (Eggelsberg, Austria)
        description: | # this will include new lines to allow paragraphs
          These few months abroad was amazing. 
          I was part of an engineering camp with talented young people comning from all over the world.
          I took the opportunity to perfect my knowledge in industrial automation while improving my english.
      - layout: left
        title: TECNAL S.A.
        link: Tecnal.fr
        # link_text: boringcompany.com
        sub_title: Automation design office
        caption: Sept 2008 - Aug 2009 (Niort)
        description: | # this will include new lines to allow paragraphs
          Tecnal is a specialist in dairy and cheese equipment. I worked as automation & adjuster technician.
          I was mainly on the field, either in France or abroad, learning on special machines mainly in process industry.
          
          

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Poitiers
        caption: 2005 - 2008
        sub_title: MSc in Industrial Automation & mecatronic
        description: | # this will include new lines to allow paragraphs
          During my first year at University of Poitiers I learnt most deppen our basics skills.
          At that time, our teachers were mostly from research department called [PPrime](https://pprime.fr/en/home-pprime/). 
          They were really dynamic and enthusiastic about mecatronic and especially skilled medical robotic.
          I got really passionate too, that's why I specialized in mecatronic for the two last year of my master degree.
          Funny fact, I became teacher for a few days of my old teacher.
      - layout: left
        title: University of Lorient
        caption: 2003 - 2005
        sub_title: BTEC in Industrial Maintenance
        description: | # this will include new lines to allow paragraphs
          This two year gave me the opportunity to learn the basis on almost every domain of the industry as maintenance is a very large topic.
          I had the opportunity to do an internship in an Automotive company called PSA Peugeot Citroen.
          My goal was to make preventive maintenance sheets as I was part of TPM service.
          But everytime I could, I was near machines, looking at the robot and asking so many questions.
      - layout: left
        title: High School A.R. Lesage in Vannes
        caption: 2003
        sub_title: BD In Mechanical Engineering
        description: | # this will include new lines to allow paragraphs
          During my time at high school, I specialized in mecanics.
          What I really liked, courses was separated in two parts, theoretical courses surch as Mechanical drawing , Kinematic, Electrical, etc..
          And practical courses where I could use conventional milling, CNC and molding machines for the first time.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      During my spare time, I also Have interests in networks and software engineering. I have a passion for domotic and IoT which brings me some basis knowledge on several domain like:
      - Linux
      - Javascript
      - Php 
      - Docker
      - MQTT
      - ...
      
      But I'm not staying in front of my computer all the time. I do a lot of sport such as running and mountain biking.
      As I'm not far from the ocean, Surf and SUP are some activities I do like during summer. 
      I used to be a football player for many years, still passionate but not pacticing anymore.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
