# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mathieu Tanguy
title: Mecatronic Engineer
email: mathieu@tanguym.eu
address: 11 rue Saint Michel, 44260 Savenay FRANCE
# website: https://mttng.github.io/online-resume/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: mttng
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Light version
  icon: fas fa-feather
  url: https://resume.tanguym.eu
- title: Location
  icon: fas fa-map
  url: https://www.google.fr/maps/place/11+Rue+Saint-Michel,+44260+Savenay/@46.320004,3.2451541,5.63z/data=!4m5!3m4!1s0x4805817a25b76c03:0x5767a922f0c11aae!8m2!3d47.3622972!4d-1.9424031
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a mecatronic engineer with over 14 years experience in industrial automation.
  <br>
  I like to work on challenging projects, independently, or as a team member.
  <br>
  Being curious and creative help me to push my limits everyday.
  My willingness to help and understand customer or colleague needs brings good working relationships based on trust.
  <br>
  My position as technical office manager enforce my links with sales department and help me to improve soft skills like scheduling, priorisation or strategic decision-making.
  <br>
  Thanks to my experience working for an innovative supplier, I developped knowledges on many solutions in different industries of industrial automation.
  Even though I'm most skilled in:
  <br>
  <mark>Software architecture</mark> <mark>Motion control</mark> <mark>CNC</mark> <mark>Robotic</mark> <mark>IEC 61131-3</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Linear transport system
        # link: https://www.youtube.com/watch?v=VJN8IgHODj4
        # link_text: Machine presentation
        additional_links:
          - title:  Acopostrak
            icon: fas fa-globe
            url: https://www.br-automation.com/en/products/mechatronic-systems/acopostrak/
          - title:  Can Collar
            icon: fa fa-youtube
            url: https://www.youtube.com/watch?v=VJN8IgHODj4
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Machine is fully <mark>flexible</mark> and <mark>modular</mark>, it groups different can sizes by 2, 3, 4 and more with almost no change over.
          In addition to magnetic conveyor called <mark>Acopostrak</mark>, I used advanced <mark>motion control</mark> features such as encoder emulation, cam profile and cyclic positionning.
          I was involved at every project stage, pre-sales, prototype, until serial production.
          For this challenging project I had the chance to be in close cooperation with R&D and other services at headquarter.
          
      - layout: left
        title: Integrated robot
        # link: https://www.youtube.com/watch?v=VJN8IgHODj4
        # link_text: Machine presentation
        additional_links:
          - title:  Cetec
            icon: fa fa-youtube
            url: https://www.youtube.com/watch?v=xE7J6ICQw88
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          <mark>Comau Robot</mark> is controlled by the PLC and fully synchronized with the rest of the machine.
          Gripper follows the height of vertical conveyor while still placing bags thanks to a tracking feature.
          On top of this application, I implemented <mark>PackML</mark>. Project handover was then made easier.
      - layout: left
        title: CNC Machine
        additional_links:
          - title:  BDM
            icon: fa fa-youtube
            url: https://www.youtube.com/watch?v=T4fu1nRZKFs
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Machine cuts and machines aluminium or plastic profiles.
          <mark>CNC</mark> engine is integrated inside the main CPU that controls more than 30 another numerical axes.
          Customer could get rid of an expensive and non modular dedicated CNC controller.
          During this first project as application engineer, I improve my hard skills as well as my soft skills through a very high demanding customer coming from full CNC contoller to an integrated CNC kernel.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: B&R Automation
        link: br-automation.com
        # link_text: boringcompany.com
        sub_title: Technical Office Manager
        caption: Feb 2018 - Present (Nantes)
        description: | # this will include new lines to allow paragraphs
            After many years as application engineer, I got promoted as technical office manager.
            I lead up to 6 local application & support engineers in Nantes office.
            My missions are to plan & prioritize technical actions while making sure my team members have enough skills to succeed.
            Even with this new responsability, I'm still involved technically in complex strategic customer projects.

      - layout: left
        title: B&R Automation
        link: br-automation.com
        # link_text: boringcompany.com
        sub_title: Application Engineer
        caption: Feb 2010 - Feb 2018 (Paris & Nantes)
        description: | # this will include new lines to allow paragraphs
          This position has been challenging for me as the spectrum is large:
          - Remote and on-site technical customer support.
          - Assist customer on his project from prototype phase to serial production.
          - Hold customer and internal training.
          - Participate to pre-sales project (presentation, hardware architecture, etc...).

          I spend 2 years in Paris then I moved to Nantes office.

      - layout: left
        title: B&R Automation
        link: https://www.br-automation.com/en/career/working-at-br/engineering-camp/
        link_text: Engineering Camp
        sub_title: Training program
        caption: Sept 2009 - Dec 2009 (Eggelsberg, AT)
        description: | # this will include new lines to allow paragraphs
          B&R Automation is one of the most innovative company in industrial automation.
          Before joining french subsidiary, I attended an engineering camp among talented young people coming from all over the world.
          I took the opportunity to perfect my knowledge in industrial automation while improving my english.
      - layout: left
        title: TECNAL S.A.
        link: https://www.tecnal.fr/en/home/
        # link_text: boringcompany.com
        sub_title: Automation design office
        caption: Sept 2008 - Aug 2009 (Niort)
        description: | # this will include new lines to allow paragraphs
          Tecnal is a specialist in dairy and cheese equipment. I worked as automation & adjuster technician.
          I was mainly on the field, either in France or abroad, learning on special machines in process industry.
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Poitiers
        caption: 2005 - 2008
        sub_title: MSc in Industrial Automation & Mecatronic
        description: | # this will include new lines to allow paragraphs
          During my first year at University of Poitiers I deppened my basics skills.
          At that time, our teachers were mostly coming from research department called [PPrime](https://pprime.fr/en/home-pprime/). 
          They were really dynamic and enthusiastic about mecatronic and especially skilled in medical robotic.
          I got really passionate too, that's why I specialized in mecatronic for the two last year of my master degree.
          Funny fact, I became teacher for a few days of my old teacher.
      - layout: left
        title: University of Lorient
        caption: 2003 - 2005
        sub_title: BTEC in Industrial Maintenance
        description: | # this will include new lines to allow paragraphs
          I learn basis on almost every domain of the industry as maintenance is a very large topic.
          I did an internship in an Automotive company called PSA Peugeot Citroen.
          My goal was to make preventive maintenance sheets as I was part of TPM service.
          But everytime I could, I was near machines, looking at the robot asking so many questions.
      - layout: left
        title: High School A.R. Lesage in Vannes
        caption: 2003
        sub_title: BD In Mechanical Engineering
        description: | # this will include new lines to allow paragraphs
          During my time at high school, I specialized in mecanics.
          I had theoretical courses such as mechanical drawing , kinematic, electrical, etc..
          And practical courses where I could use conventional milling, CNC and molding machines for the first time.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I like to spend time with my family and friends, it is a good way to switch off.
      <br>
      During my personal spare time, I have interests in domotics and IoT that brings me some basis knowledges on several domains like: 
      <br>
      <mark>Linux</mark> <mark>HTML</mark> <mark>Javascript</mark> <mark>Php</mark> <mark>Docker</mark> <mark>MQTT</mark> <mark>Git</mark> <mark>SQL</mark> 
      <br>
      Which are becoming more and more popular in industrial automation.
      
      But I'm not staying in front of my computer all the time. I like to go running and sometimes mountain biking.
      As I'm not far from the ocean, SUP is an activity I do like during summer.
      My passion for music brings me regurlarly to concert and music festival.
      I used to be a football player for many years, still passionate but not practicing anymore.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
